/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.haila.formulario;

import Singleton.SEnfermeira;
import Singleton.SPaciente;
import Singleton.STriagem;
import br.com.haila.objeto.Enfermeira;
import br.com.haila.objeto.Paciente;
import br.com.haila.objeto.Triagem;
import javax.swing.JOptionPane;

/**
 *
 * @author SATC
 */
public class FTriagem extends javax.swing.JFrame {

    /**
     * Creates new form Triagem
     */
    public FTriagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTAlergias = new javax.swing.JTextField();
        jTEnfermeira = new javax.swing.JTextField();
        jTPeso = new javax.swing.JTextField();
        jTPaciente = new javax.swing.JTextField();
        jTAltura = new javax.swing.JTextField();
        jTPressao = new javax.swing.JTextField();
        JTImc = new javax.swing.JTextField();
        jTTemperatura = new javax.swing.JTextField();
        jTFebre = new javax.swing.JTextField();
        jTSintomas = new javax.swing.JTextField();
        jLAlergias = new javax.swing.JLabel();
        jLEnfermeira = new javax.swing.JLabel();
        jLPeso = new javax.swing.JLabel();
        jLPaciente = new javax.swing.JLabel();
        jLAltura = new javax.swing.JLabel();
        jLPressao = new javax.swing.JLabel();
        jLImc = new javax.swing.JLabel();
        jLTemperatura = new javax.swing.JLabel();
        jLFebre = new javax.swing.JLabel();
        jLSintomas = new javax.swing.JLabel();
        jBCadastrar = new javax.swing.JButton();
        jBMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Triagem ");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(240, 240, 240), null));

        jTEnfermeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTEnfermeiraActionPerformed(evt);
            }
        });

        jLAlergias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLAlergias.setText("Alergias:");
        jLAlergias.setName("jLAlergias"); // NOI18N

        jLEnfermeira.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLEnfermeira.setText("Enfermeira:");
        jLEnfermeira.setName("jLEnfermeira"); // NOI18N

        jLPeso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLPeso.setText("Peso:");
        jLPeso.setName("jLPeso"); // NOI18N

        jLPaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLPaciente.setText("Paciente:");
        jLPaciente.setName("jLPaciente"); // NOI18N

        jLAltura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLAltura.setText("Altura:");
        jLAltura.setName("jLAltura"); // NOI18N

        jLPressao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLPressao.setText("Pressão:");
        jLPressao.setName("jLPressao"); // NOI18N

        jLImc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLImc.setText("IMC:");
        jLImc.setName("jLImc"); // NOI18N

        jLTemperatura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLTemperatura.setText("Temperatura:");
        jLTemperatura.setName("jLTemperatura"); // NOI18N

        jLFebre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLFebre.setText("Febre:");
        jLFebre.setName("jLFebre"); // NOI18N

        jLSintomas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLSintomas.setText("Sintomas:");
        jLSintomas.setName("jLSintomas"); // NOI18N

        jBCadastrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        jBMostrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBMostrar.setText("Mostrar");
        jBMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLSintomas)
                            .addComponent(jLTemperatura)
                            .addComponent(jLPressao)
                            .addComponent(jLPaciente)
                            .addComponent(jTEnfermeira, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jTPaciente)
                            .addComponent(jTPressao)
                            .addComponent(jTTemperatura)
                            .addComponent(jTSintomas))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLAlergias)
                            .addComponent(jLPeso)
                            .addComponent(jLAltura)
                            .addComponent(jLImc)
                            .addComponent(jLFebre)
                            .addComponent(jTAlergias, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(jTPeso)
                            .addComponent(jTAltura)
                            .addComponent(JTImc)
                            .addComponent(jTFebre)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jBCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(jBMostrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLEnfermeira)
                    .addContainerGap(236, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLAlergias)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTEnfermeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPaciente)
                    .addComponent(jLPeso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPressao)
                    .addComponent(jLAltura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTPressao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTemperatura)
                    .addComponent(jLImc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTImc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSintomas)
                    .addComponent(jLFebre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTSintomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFebre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastrar)
                    .addComponent(jBMostrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jLEnfermeira)
                    .addContainerGap(311, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTEnfermeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTEnfermeiraActionPerformed
    
    }//GEN-LAST:event_jTEnfermeiraActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        Triagem triagem = null;
        int codigPaciente = Integer.parseInt(jTPaciente.getText());
        Paciente paciente = SPaciente.getInstance().getPacientes().get(codigPaciente);
        int codigEnfermeira = Integer.parseInt(jTEnfermeira.getText());
        Enfermeira enfermeira = SEnfermeira.getInstance().getEnfermeira().get(codigEnfermeira);
        String pressao = jTPressao.getText();
        float temperatura= Float.parseFloat(jTPressao.getText());
        String sintomas = jTSintomas.getText();
        String alergias = jTAlergias.getText();
        float peso = Float.parseFloat(jTPeso.getText());
        float altura = Float.parseFloat(jTAltura.getText());
        float imc = Float.parseFloat(JTImc.getText());
        Boolean febre = Boolean.parseBoolean(jTFebre.getText());
        STriagem.getInstance().getTriagem().add(triagem);
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jBMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMostrarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jBMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FTriagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTImc;
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBMostrar;
    private javax.swing.JLabel jLAlergias;
    private javax.swing.JLabel jLAltura;
    private javax.swing.JLabel jLEnfermeira;
    private javax.swing.JLabel jLFebre;
    private javax.swing.JLabel jLImc;
    private javax.swing.JLabel jLPaciente;
    private javax.swing.JLabel jLPeso;
    private javax.swing.JLabel jLPressao;
    private javax.swing.JLabel jLSintomas;
    private javax.swing.JLabel jLTemperatura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTAlergias;
    private javax.swing.JTextField jTAltura;
    private javax.swing.JTextField jTEnfermeira;
    private javax.swing.JTextField jTFebre;
    private javax.swing.JTextField jTPaciente;
    private javax.swing.JTextField jTPeso;
    private javax.swing.JTextField jTPressao;
    private javax.swing.JTextField jTSintomas;
    private javax.swing.JTextField jTTemperatura;
    // End of variables declaration//GEN-END:variables
}
